-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Aug 14, 2023 at 01:50 AM
-- Server version: 10.5.16-MariaDB
-- PHP Version: 8.2.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `next_teikoku_mangas_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `compra`
--

CREATE TABLE `compra` (
  `id` int(11) NOT NULL,
  `idUsuario` int(11) DEFAULT NULL,
  `total` decimal(5,2) DEFAULT NULL,
  `fecha_compra` date DEFAULT NULL,
  `token` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `confirmado` tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `compra`
--

INSERT INTO `compra` (`id`, `idUsuario`, `total`, `fecha_compra`, `token`, `confirmado`) VALUES
(1, 5, 188.00, '2023-08-13', '', 1),
(2, 5, 0.00, '2023-08-13', '64d983dfc9fd4', 0);

-- --------------------------------------------------------

--
-- Table structure for table `detalle_compra`
--

CREATE TABLE `detalle_compra` (
  `id` int(11) NOT NULL,
  `manga_id` int(11) DEFAULT NULL,
  `compra_id` int(11) DEFAULT NULL,
  `precio_unitario` decimal(5,2) DEFAULT NULL,
  `cantidad` int(11) DEFAULT NULL,
  `precio_venta` decimal(5,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `detalle_compra`
--

INSERT INTO `detalle_compra` (`id`, `manga_id`, `compra_id`, `precio_unitario`, `cantidad`, `precio_venta`) VALUES
(1, 3, 1, 68.00, 1, 68.00),
(2, 42, 1, 60.00, 2, 120.00);

-- --------------------------------------------------------

--
-- Table structure for table `producto`
--

CREATE TABLE `producto` (
  `id` int(11) NOT NULL,
  `Titulo` varchar(50) DEFAULT NULL,
  `Descripcion` varchar(1000) DEFAULT NULL,
  `Precio` decimal(5,2) DEFAULT NULL,
  `Autor` varchar(50) DEFAULT NULL,
  `Editorial` varchar(50) DEFAULT NULL,
  `fecha_lanzamiento` date DEFAULT NULL,
  `imagenes` varchar(200) DEFAULT NULL,
  `Categoría` varchar(20) DEFAULT NULL,
  `Popularidad` decimal(5,2) DEFAULT NULL,
  `stock` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `producto`
--

INSERT INTO `producto` (`id`, `Titulo`, `Descripcion`, `Precio`, `Autor`, `Editorial`, `fecha_lanzamiento`, `imagenes`, `Categoría`, `Popularidad`, `stock`) VALUES
(1, 'Dragon Ball Z', 'La historia se desarrolla después de los eventos de \"Dragon Ball Z\" y muestra a Goku y sus aliados enfrentándose a enemigos aún más poderosos. La trama se centra en los combates épicos en los torneos de artes marciales interdimensionales, donde participan peleadores de diferentes universos.A medida que la historia avanza, se introducen nuevos personajes, como el dios de la destrucción Bills y su asistente Whis, así como otros dioses y seres cósmicos. Goku y sus amigos se enfrentan a desafíos que ponen en peligro no solo a la Tierra, sino a todo el multiverso.El manga \"Dragon Ball Super\" combina acción, comedia y momentos emocionales, al igual que sus predecesores. Los personajes icónicos, como Goku, Vegeta, Piccolo y otros, siguen evolucionando y entrenando para alcanzar nuevos niveles de poder.', 60.00, 'Akira Toriyama', 'Shūeisha', '1984-11-20', 'DragonBall.jpg', 'Shonen', 10.00, 50),
(2, 'One Punch Man', 'La historia gira en torno a Saitama, un hombre común que se ha vuelto tan poderoso que puede derrotar a cualquier enemigo con un solo puñetazo. Sin embargo, a pesar de su increíble fuerza, Saitama se siente abrumado por la falta de desafío en sus batallas y se encuentra en un estado de aburrimiento y apatía.\r\n\r\nA lo largo del manga, Saitama se encuentra con varios enemigos y se une a la Asociación de Héroes, donde se enfrenta a monstruos y villanos de todo tipo. Aunque sigue siendo invencible, Saitama busca desesperadamente un oponente digno que pueda desafiarlo y despertar su pasión por la lucha.', 45.00, 'One y Yusuke Murata', 'Shūeisha', '2012-06-14', 'OnePunchMan.jpg', 'Shonen', 8.00, 10),
(3, 'One piece', 'Luffy, un chico con habilidades elásticas después de comer una fruta del diablo, busca convertirse en el próximo Rey de los Piratas.\r\n\r\nLa historia se desarrolla en un vasto mundo lleno de islas, océanos y criaturas fantásticas. Luffy, junto a su tripulación, llamada los Piratas del Sombrero de Paja, se enfrenta a numerosos desafíos y enemigos poderosos mientras navegan por los mares Grand Line y New World. Su objetivo principal es encontrar el One Piece, un tesoro que les otorgará fama, riquezas y el título de Rey de los Piratas.\r\n\r\nA lo largo del manga, Luffy recluta a nuevos miembros para su tripulación, cada uno con habilidades únicas y una historia personal. Juntos, se enfrentan a gobiernos corruptos, otros piratas, la Marina y diversas facciones que buscan impedirles alcanzar su objetivo.', 68.00, 'Eiichirō Oda', 'Shūeisha', '1997-07-22', 'OnePiece.jpg', 'Shonen', 10.00, 46),
(4, 'Fullmetal Alchemist', 'La historia se desarrolla en un mundo ficticio donde la alquimia es una ciencia avanzada y se utiliza para manipular la materia.\r\n\r\nLos protagonistas son los hermanos Edward y Alphonse Elric, quienes buscan desesperadamente encontrar la piedra filosofal para restaurar sus cuerpos después de un intento fallido de resucitar a su madre usando la alquimia. Edward pierde una pierna y un brazo, mientras que Alphonse pierde completamente su cuerpo, y su alma se fusiona con una armadura.\r\n\r\nLos hermanos Elric se embarcan en un viaje lleno de peligros y descubren una conspiración más grande relacionada con la piedra filosofal. A medida que exploran el mundo y se enfrentan a diversos personajes, incluidos alquimistas corruptos y criaturas míticas, deben lidiar con las consecuencias morales y éticas de sus acciones y enfrentar las duras realidades de la vida.', 58.00, 'Hiromu Arakawa', 'Square Enix', '2001-08-12', 'FullMetalAlchemist.png', 'Shonen', 8.70, 10),
(5, 'Nanatsu no Taizai', 'La historia se desarrolla en un mundo medieval donde los Caballeros Sagrados, una orden de guerreros poderosos, protegen el reino de Britannia. Sin embargo, cuando los Caballeros Sagrados traicionan al reino y toman el control, los siete pecados capitales, un grupo de poderosos ex caballeros, se convierten en los forajidos más buscados.\r\n\r\nCada uno de los Siete Pecados Capitales representa un pecado capital y tiene habilidades y personalidades únicas. Meliodas, el líder del grupo, es conocido como el Pecado de la Ira, mientras que Elizabeth, la princesa del reino, se une a los Pecados Capitales para derrocar a los Caballeros Sagrados y salvar a Britannia.', 49.00, 'Nakaba Suzuki', 'Kōdansha', '2012-10-10', 'NanatsuNoTaizai.jpg', 'Shonen', 7.50, 10),
(6, 'Naruto', 'La historia se desarrolla en un mundo ninja y sigue las aventuras de Naruto Uzumaki, un joven ninja hiperactivo y soñador que busca convertirse en el Hokage, el líder y protector de su aldea.\r\n\r\nNaruto es un niño con un pasado trágico, ya que alberga en su interior al Zorro de Nueve Colas, una poderosa bestia con un poder destructivo. A lo largo del manga, Naruto se esfuerza por ganarse el respeto y la aceptación de sus compañeros ninja, superar desafíos y proteger a sus seres queridos.\r\n\r\nEl manga explora temas como la amistad, el coraje, la superación personal y la importancia de los lazos familiares. A medida que la historia avanza, Naruto y sus amigos se enfrentan a peligrosos enemigos, participan en batallas épicas y desvelan conspiraciones que amenazan la paz en su mundo.', 60.00, 'Masashi Kishimoto', 'Shūeisha', '1999-09-21', 'Naruto.jpg', 'Shonen', 9.90, 7),
(7, 'My Hero Academia', 'La historia se desarrolla en un mundo donde la mayoría de la población tiene superpoderes conocidos como \"Quirks\". El protagonista, Izuku Midoriya, es un joven fanático de los héroes que sueña con convertirse en uno de ellos a pesar de no tener un Quirk propio.\r\n\r\nSin embargo, la vida de Izuku cambia cuando se encuentra con su héroe favorito, All Might, quien le revela que ha heredado su poder y decide convertirse en su mentor. Izuku ingresa a la Academia U.A., una prestigiosa escuela de héroes, donde se encontrará con otros estudiantes con habilidades sobrenaturales y se enfrentará a diversos desafíos para mejorar y convertirse en un héroe profesional.\r\n\r\nA lo largo del manga, Izuku y sus compañeros de clase se enfrentan a villanos poderosos, participan en combates intensos y exploran los límites de sus habilidades. La serie aborda temas como el sacrificio, la amistad, la perseverancia y la responsabilidad que conlleva ser un héroe.', 55.00, 'Kōhei Horikoshi', 'Shūeisha', '2014-07-07', 'MyHeroAcademia.png', 'Shonen', 8.40, 9),
(8, 'Hunter x Hunter', 'La historia sigue las aventuras de Gon Freecss, un niño de doce años que desea convertirse en un cazador, una élite de individuos que se dedican a explorar lugares peligrosos, buscar tesoros ocultos y cazar criaturas exóticas.\r\n\r\nGon se embarca en un viaje para encontrar a su padre, quien también es un cazador y lo abandonó cuando era un bebé. Durante su travesía, Gon conoce a otros aspirantes a cazadores y se enfrenta a diversos desafíos que ponen a prueba su habilidad, inteligencia y coraje.\r\n\r\nA medida que la historia avanza, \"Hunter x Hunter\" se desarrolla en un mundo complejo lleno de personajes fascinantes y situaciones intrigantes. Explora temas como la amistad, la lealtad, el sacrificio y la búsqueda de significado en la vida. La serie también aborda cuestiones éticas y morales a medida que los personajes se enfrentan a decisiones difíciles y enfrentamientos con enemigos poderosos.', 75.00, 'Yoshihiro Togashi', 'Shūeisha', '1998-03-03', 'HunterxHunter.jpg', 'Shonen', 9.00, 7),
(9, 'Kimetsu no Yaiba', 'La historia se sitúa en un Japón ficticio durante la era Taisho y sigue a Tanjiro Kamado, un joven bondadoso y dedicado que se convierte en un cazador de demonios después de que su familia es brutalmente asesinada por un demonio, y su hermana Nezuko se transforma en uno.\r\n\r\nTanjiro se une a la organización de cazadores de demonios para encontrar una cura para su hermana y vengar a su familia. A lo largo de su viaje, Tanjiro y Nezuko se enfrentan a demonios poderosos y descubren los secretos detrás de su transformación. Se encuentran con otros cazadores de demonios, cada uno con sus propias habilidades y personalidades, y forman un equipo para luchar contra las fuerzas demoníacas.', 67.00, 'Koyoharu Gotouge', 'Shūeisha', '2016-02-15', 'KimetsuNoYaiba.jpg', 'Shonen', 8.80, 8),
(10, 'Bleach', 'La historia sigue las aventuras de Ichigo Kurosaki, un adolescente con la habilidad de ver espíritus. Un día, Ichigo obtiene los poderes de un Shinigami, un ser encargado de proteger a los vivos de los espíritus malignos conocidos como Hollows.\r\n\r\nA medida que Ichigo explora su nuevo rol como Shinigami, se involucra en batallas contra Hollows cada vez más peligrosos y se encuentra con otros Shinigamis y seres espirituales. Descubre la existencia de la Sociedad de Almas, una organización de Shinigamis que supervisa el equilibrio entre el mundo de los vivos y el de los espíritus.\r\n\r\nA lo largo del manga, Ichigo se enfrenta a numerosos enemigos poderosos, descubre secretos oscuros y se involucra en conflictos que amenazan la paz en ambos mundos. La historia también explora la amistad, la lealtad y el sacrificio mientras los personajes luchan por proteger a sus seres queridos y cumplir su deber como Shinigamis.', 50.00, 'Tite Kubo', 'Shūeisha', '2001-08-07', 'Bleach.jpg', 'Shonen', 7.50, 10),
(11, 'Haikyuu', 'La historia se centra en el equipo de voleibol de la escuela secundaria Karasuno, que busca alcanzar la grandeza en el deporte. El protagonista principal es Shoyo Hinata, un jugador de baja estatura pero con una gran pasión y habilidad para el voleibol.\r\n\r\nHinata se une al equipo de voleibol de Karasuno y trabaja duro para mejorar sus habilidades y superar los obstáculos que se presentan en su camino. Junto con sus compañeros de equipo, incluido el talentoso jugador Tobio Kageyama, Hinata se esfuerza por convertirse en un jugador destacado y llevar a Karasuno a la victoria en los torneos de voleibol.', 50.00, 'Haruichi Furudate', 'Shūeisha', '2012-02-20', 'Haykyuu.jpg', 'Deporte', 7.90, 10),
(12, 'Slam Dunk', 'La historia sigue a Hanamichi Sakuragi, un estudiante de secundaria problemático y de gran altura que se une al equipo de baloncesto de la escuela Shohoku con la esperanza de impresionar a una chica que le gusta.\r\n\r\nInicialmente, Hanamichi no tiene experiencia en el baloncesto y carece de habilidades básicas, pero su pasión y talento natural para el juego comienzan a florecer a medida que se involucra más en el deporte. Junto con sus compañeros de equipo, incluido el talentoso Kaede Rukawa, Hanamichi se enfrenta a diferentes equipos y se esfuerza por alcanzar la gloria en los torneos de baloncesto de la escuela.', 40.00, 'Takehiko Inoue', ' Shūeisha', '1990-10-01', 'SlamDunk.jpg', 'Deporte', 6.90, 10),
(13, 'Blue lock', 'La historia se desarrolla en un mundo donde el fútbol japonés ha caído en decadencia y se crea un programa especial llamado \"Blue Lock\". Este programa reúne a los mejores delanteros del país en una institución de élite con el objetivo de desarrollar al próximo gran delantero de clase mundial.\r\n\r\nEl protagonista, Yoichi Isagi, es un talentoso delantero que es invitado a unirse a Blue Lock. Allí, se enfrenta a un ambiente competitivo y despiadado, ya que los delanteros luchan entre sí para convertirse en el único elegido que liderará al equipo nacional. Isagi se enfrenta a desafíos tanto en el campo como fuera de él, mientras lucha por encontrar su propio estilo de juego y superar a sus compañeros y rivales.', 55.00, ' Muneyuki Kaneshiro y Yusuke Nomura', 'Kōdansha', '2018-08-02', 'BlueLock.jpg', 'Deporte', 9.60, 49),
(14, 'Capitán Tsubasa', 'La historia gira en torno a Tsubasa Ozora, un joven prodigio del fútbol que sueña con convertirse en el mejor jugador del mundo. Desde una edad temprana, Tsubasa muestra habilidades extraordinarias y un amor apasionado por el fútbol.\r\n\r\nA medida que avanza la trama, Tsubasa se enfrenta a diferentes desafíos y participa en emocionantes partidos y competiciones a nivel nacional e internacional. A través de su dedicación, determinación y trabajo en equipo, Tsubasa y sus compañeros luchan por alcanzar la victoria y superar a rivales formidables.', 56.00, 'Yōichi Takahashi', 'Shūeisha', '1981-05-13', 'CapitanTsubasa.png', 'Deporte', 8.80, 7),
(15, 'Kuroko no Basket', 'La historia se centra en el equipo de baloncesto de la escuela secundaria Teiko, conocido por su dominio absoluto en el deporte. Sin embargo, lo que hace que Teiko sea tan temido no son solo sus cinco jugadores titulares estrella, sino también un sexto jugador enigmático y poco destacado: Tetsuya Kuroko.\r\n\r\nAunque Kuroko carece de habilidades físicas impresionantes, es un jugador con un talento único: es un maestro en el arte del juego en equipo y la invisibilidad en la cancha. Después de graduarse de Teiko, Kuroko se une al equipo de baloncesto de la escuela secundaria Seirin, donde conoce a Taiga Kagami, un talentoso jugador con una gran presencia en la cancha.\r\n\r\nJuntos, Kuroko y Kagami forman una dupla dinámica y desafían a los equipos de baloncesto más fuertes de Japón. Su objetivo es derrotar a la \"Generación de los Milagros\", los antiguos compañeros de Kuroko en Teiko, quienes ahora están dispersos en diferentes escuelas y también se destacan por sus habilidades excepcionales.', 40.00, 'Tadatoshi Fujimaki', 'Shūeisha', '2014-09-01', 'KurokoNoBasket.jpg', 'Deporte', 7.40, 10),
(16, 'Ace of Diamond ', 'La historia se centra en Eijun Sawamura, un joven lanzador de béisbol con una pasión desbordante por el deporte. Eijun es reclutado por la prestigiosa escuela secundaria Seidou, conocida por su equipo de béisbol de alto nivel.\r\n\r\nEn Seidou, Eijun se encuentra con jugadores talentosos y dedicados que compiten en torneos nacionales. Junto con sus compañeros de equipo, Eijun se esfuerza por convertirse en el mejor lanzador y ayudar a Seidou a alcanzar la victoria. En el camino, se enfrenta a desafíos tanto en el campo como fuera de él, superando obstáculos, perfeccionando sus habilidades y desarrollando un fuerte espíritu de equipo.', 44.00, 'Yuji Terajima', 'Kōdansha', '2006-05-17', 'AceOfDiamond.png', 'Deporte', 7.30, 10),
(17, 'Ao Ashi', 'La historia sigue a Ashito Aoi, un estudiante de secundaria apasionado por el fútbol. Aunque Ashito no destaca físicamente, posee una visión y un sentido del juego excepcionales.\r\n\r\nUn día, Ashito es reclutado por el equipo de fútbol de su escuela secundaria, que ha tenido un desempeño mediocre en el pasado. Con su talento y habilidad para leer el juego, Ashito se convierte en el centro de atención del equipo y comienza a guiarlos hacia la victoria.\r\n\r\n\"Ao Ashi\" destaca por su enfoque realista del fútbol y su representación precisa de las tácticas y estrategias utilizadas en el juego. La serie también aborda los desafíos y obstáculos que Ashito y su equipo enfrentan en su camino hacia la excelencia, incluyendo rivales talentosos, presiones y expectativas sociales.', 35.00, 'Yūgo Kobayashi', 'Kodansha', '2015-01-06', 'AoAshi.jpeg', 'Deporte', 6.40, 6),
(18, 'Hajime no Ippo', 'La historia sigue la vida de Ippo Makunouchi, un tímido estudiante de secundaria que constantemente es objeto de intimidación. Un día, Ippo es rescatado por Mamoru Takamura, un boxeador profesional, y se siente inspirado por su fuerza y habilidad.\r\n\r\nImpresionado por el mundo del boxeo, Ippo decide entrenar y convertirse en un boxeador él mismo. Con el apoyo de Takamura y otros miembros del gimnasio Kamogawa, Ippo comienza su viaje en el mundo del boxeo. A medida que progresa en su entrenamiento, Ippo enfrenta desafíos físicos y mentales, descubriendo sus propias fortalezas y debilidades en el ring.\r\n\"Hajime no Ippo\" se centra en las peleas de boxeo, ofreciendo emocionantes combates llenos de estrategia, técnica y superación personal. El manga explora los altibajos de la carrera de Ippo, así como las relaciones con sus compañeros de gimnasio, su vida personal y las rivalidades en el mundo del boxeo.', 55.00, 'George Morikawa', 'Kodansha', '1989-10-27', 'HajimeNoIppo.jpg', 'Deporte', 9.00, 6),
(19, 'Ping Pong', 'La historia se desarrolla en el mundo del tenis de mesa y sigue las vidas de dos jóvenes talentosos: Peko y Smile.\r\n\r\nPeko es un jugador de tenis de mesa naturalmente talentoso y carismático. Es conocido por su estilo de juego agresivo y su pasión por el deporte. Por otro lado, Smile es un chico reservado y aparentemente sin emociones, pero posee habilidades asombrosas en el tenis de mesa.\r\n\r\nA medida que la trama avanza, se exploran las relaciones y los conflictos de los personajes, sus sueños y sus desafíos personales. La historia se adentra en temas más profundos, como la amistad, la rivalidad, la identidad personal y la búsqueda del significado en la vida', 32.00, 'Taiyō Matsumoto', 'Shogakukan', '1996-05-10', 'PingPong.jpg', 'Deporte', 5.40, 10),
(20, 'Inazuma Eleven', 'La historia gira en torno a un joven llamado Mamoru Endou, un apasionado del fútbol y capitán del equipo de fútbol de la escuela Raimon.\r\n\r\nUn día, un misterioso portero llamado Gouenji Shuuya se une al equipo de Mamoru. Juntos, forman un equipo para participar en el torneo de fútbol y enfrentarse a otros equipos poderosos. A medida que avanza la trama, Mamoru y su equipo deben superar desafíos, perfeccionar sus habilidades y enfrentarse a rivales formidables para alcanzar la victoria.\r\n\r\nEl manga combina acción, comedia y drama, y muestra emocionantes partidos de fútbol con movimientos especiales y técnicas sobrenaturales. Además de los aspectos deportivos, \"Inazuma Eleven\" también presenta el crecimiento personal de los personajes, sus amistades y la importancia del trabajo en equipo.', 50.00, 'Tenya Yabuno', 'Shogakukan', '2008-05-15', 'InazumaEleven.jpg', 'Deporte', 8.00, 10),
(21, 'Ao Haru Ride ', 'La historia se centra en Futaba Yoshioka, una joven estudiante de secundaria que solía ser popular entre los chicos en la escuela primaria. Sin embargo, debido a un malentendido, Futaba decide cambiar su personalidad y apariencia para evitar ser malinterpretada por los demás.\r\n\r\nEn su primer año de secundaria, Futaba se reencuentra con su amor de la infancia, Kou Tanaka, quien ahora se hace llamar Kou Mabuchi. Aunque inicialmente están distanciados, la conexión entre ellos se reaviva y comienzan a desarrollar sentimientos el uno por el otro.\r\n\r\n\"Ao Haru Ride\" explora la complicada relación entre Futaba y Kou mientras enfrentan obstáculos emocionales y aprenden a superar su pasado. La serie toca temas como la amistad, el amor no correspondido, la confianza y el crecimiento personal. A través de personajes carismáticos y momentos conmovedores, el manga captura las emociones y los altibajos de la juventud y el romance.', 47.00, 'Io Sakisaka', 'Shueisha', '2011-01-13', 'aoharu.jpg', 'Shoujo', 7.00, 10),
(22, 'La blancanieves peliroja', 'La historia sigue la vida de Shirayuki, una joven pelirroja con un cabello muy llamativo. Ella es una herbalista talentosa y vive en el reino de Tanbarun.\r\n\r\nCuando el príncipe del reino, Raji, se enamora de su distintivo cabello rojo y la declara suya, Shirayuki decide huir y buscar una vida independiente. Durante su escape, se encuentra con Zen Wistalia, un príncipe del reino vecino de Clarines. Impresionado por la determinación y habilidades de Shirayuki, Zen la invita a quedarse en su reino y se convierten en amigos cercanos.\r\n\r\nA lo largo de la historia, Shirayuki trabaja en el castillo de Clarines como herbalista y se enfrenta a diversos desafíos mientras navega por las intrigas políticas, los problemas de la realeza y los sentimientos románticos. Con su espíritu valiente y su habilidad para superar obstáculos, Shirayuki se gana el respeto y la admiración de aquellos a su alrededor.', 40.00, 'Sorata Akizuki', 'Hakusensha', '2006-08-10', 'AkagamiNoShirayukiHime.jpeg', 'Shoujo', 4.00, 10),
(23, 'Akatsuki no Yona', 'La historia sigue la vida de la princesa Yona, la única heredera del reino de Kouka. Al principio, Yona lleva una vida privilegiada y protegida en el castillo junto a su amigo de la infancia y amor platónico, el apuesto príncipe Soo-won.\r\n\r\nSin embargo, todo cambia drásticamente el día de su 16º cumpleaños, cuando Soo-won asesina a su padre y toma el trono. Yona, en un intento desesperado por sobrevivir, huye del castillo con la ayuda de su leal guardaespaldas, Hak. Juntos, se embarcan en un viaje para reunir a los legendarios dragones que una vez protegieron el reino de Kouka.\r\n\r\nA medida que Yona recorre el reino y se encuentra con los dragones, descubre su propio poder y aprende a convertirse en una líder valiente y determinada. A lo largo de la historia, Yona se enfrenta a numerosos peligros, se encuentra con diversos personajes, y se desarrolla una historia de amistad, romance y lucha por la justicia.', 46.00, 'Mizuho Kusanagi', 'Hakusensha', '2009-08-04', 'AkatsukiNoYona.png', 'shoujo', 3.40, 10),
(24, 'El principe del mar', 'Para Matori, Mugi vive como un auténtico príncipe. Pese a no llevarse bien con sus hermanos, cuando va a casa de Matori, su abuela le cuenta historias de una sirena capaz de hacer los deseos realidad…', 35.00, 'Kaori Ozaki', 'Delcourt', '2020-02-25', 'elprincipe.jpg', 'shoujo', 3.00, 9),
(25, 'Boku to Kimi no Taisetsu na Hanashi', 'La historia se centra en dos chicas, Yano Hinaki y Kano Miyu, que tienen personalidades y circunstancias de vida muy diferentes.\r\n\r\nYano es una chica popular y extrovertida que tiene muchos amigos y siempre está rodeada de gente. Por otro lado, Kano es más introvertida y tímida, y prefiere pasar tiempo sola en lugar de socializar.\r\n\r\nA pesar de sus diferencias, Yano y Kano se encuentran y forman una conexión especial. A medida que comparten experiencias, secretos y emociones, su relación se va desarrollando y profundizando. A lo largo del manga, exploran temas como la amistad, la confianza, el amor y el crecimiento personal.', 35.00, 'Robico', 'Shueisha', '2015-11-26', 'BokuToKimiNoTaisetsu.jpg', 'shoujo', 4.00, 10),
(26, 'Your lie in April', 'La historia sigue a Kōsei Arima, un prodigioso pianista que perdió la capacidad de escuchar el sonido del piano después de la muerte de su madre. Desde entonces, Kōsei ha vivido en un mundo en blanco y negro, alejado de la música y sin pasión por tocar el piano.\r\n\r\nSin embargo, todo cambia cuando conoce a Kaori Miyazono, una vibrante y talentosa violinista. Kaori irrumpe en la vida de Kōsei con su personalidad enérgica y su música cautivadora, desafiándolo a volver a tocar el piano y descubrir la belleza de la música una vez más.', 20.00, ' Naoshi Arakawa', ' Kodansha', '2011-04-13', 'YourLieInApril.jpg', 'shoujo', 3.30, 10),
(27, 'Orange', 'La historia sigue a Naho Takamiya, una estudiante de instituto que recibe una misteriosa carta de su \"yo\" del futuro. La carta contiene instrucciones detalladas sobre cómo evitar los remordimientos y arrepentimientos en la vida de Naho.\r\n\r\nLa carta se centra en la llegada de un nuevo estudiante llamado Kakeru Naruse, quien se convierte en el centro de atención de Naho y sus amigos. A medida que Naho sigue las indicaciones de la carta, se da cuenta de que Kakeru está pasando por un momento difícil y su vida está llena de dolor y tristeza.\r\n\r\nA lo largo del manga, Naho y sus amigos trabajan juntos para apoyar a Kakeru, enfrentando sus propios miedos y luchando contra el destino para tratar de cambiar el curso de los eventos y evitar una tragedia. El manga aborda temas como la amistad, el amor, la superación personal y la importancia de tomar decisiones valientes para enfrentar el pasado y forjar un futuro mejor.', 35.00, ' Ichigo Takano', 'Futabasha', '2012-03-25', 'Orange.jpg', 'shoujo', 4.40, 10),
(28, 'Hirunaka no Ryuusei', 'La historia sigue a Suzume Yosano, una estudiante de secundaria que se muda a Tokio para vivir con su tío después de que sus padres se mudan al extranjero. En su nueva escuela, Suzume se encuentra con un profesor joven y atractivo llamado Satsuki Shishio.\r\n\r\nA medida que Suzume se adapta a su nueva vida en la ciudad y lucha por encontrar su lugar en la escuela, comienza a desarrollar sentimientos por su profesor. Sin embargo, también conoce a un compañero de clase llamado Daiki Mamura, quien muestra interés en ella. Así, se desarrolla un triángulo amoroso entre Suzume, Satsuki y Daiki, mientras ellos enfrentan los desafíos de la juventud y la confusión de los sentimientos.', 32.00, 'Mika Yamamori', ' Shueisha', '2011-05-20', 'DaytimeShootngStars.jpg', 'Shoujo', 3.40, 9),
(29, 'Araburu kisetsu no otomedomo', 'La historia sigue a un grupo de cinco chicas de preparatoria que se unen al club de literatura durante el verano. A medida que se adentran en el mundo de la literatura y exploran diferentes géneros y temas, también se enfrentan a sus propias inquietudes y problemas relacionados con la pubertad y la sexualidad.\r\n\r\nEl manga aborda temas como el amor, la amistad, la identidad sexual, las presiones sociales y las expectativas culturales. Cada una de las chicas tiene su propia personalidad y enfrenta sus propios desafíos y dilemas personales, lo que crea un grupo diverso y complejo de personajes.', 45.00, 'Mari Okada y Nao Emoto', ' Kodansha', '2016-10-19', 'AraburuKisetsuNoOtomedomoYo.jpg', 'shoujo', 4.40, 10),
(30, 'Horimiya', 'La historia sigue la vida de Kyoko Hori, una estudiante popular y alegre en la escuela, y Izumi Miyamura, un chico tranquilo y poco sociable. Ambos tienen personalidades muy diferentes en su vida escolar, pero tienen un secreto: fuera de la escuela, Kyoko es una chica hogareña y responsable, mientras que Miyamura es un joven con piercings y tatuajes, con una apariencia totalmente diferente.\r\n\r\nUn día, Kyoko descubre el verdadero rostro de Miyamura cuando se encuentran fuera del horario escolar. A partir de ahí, comienza una amistad inesperada entre ellos, y poco a poco, su relación se va fortaleciendo. Juntos, descubren más sobre sus vidas, superan problemas personales y se apoyan mutuamente.', 25.00, 'Hero', 'Square Enix', '2011-10-07', 'Horimiya.jpg', 'Shoujo', 5.50, 6),
(31, 'Death Note', 'La historia gira en torno a Light Yagami, un estudiante de secundaria prodigio que encuentra un cuaderno sobrenatural conocido como Death Note. Este cuaderno tiene el poder de matar a cualquier persona cuyo nombre sea escrito en él, siempre y cuando el portador tenga en mente el rostro de la víctima mientras escribe su nombre.\r\n\r\nLight decide utilizar el Death Note para purgar el mundo de los criminales y establecer una utopía gobernada por él. A medida que las noticias de las misteriosas muertes se propagan, la sociedad comienza a llamar a este justiciero anónimo \"Kira\". Sin embargo, sus actos no pasan desapercibidos, ya que un genio detective conocido como L se propone atrapar al responsable.', 78.00, 'Tsugumi Ohba', 'Shueisha', '2003-12-01', 'deathnote.jpg', 'Terror', 9.80, 49),
(32, 'Gift', 'La historia sigue la vida de Satou, un joven estudiante de secundaria con una habilidad especial: puede leer los pensamientos de las personas al tocar sus manos. Sin embargo, esta habilidad se convierte en una carga para él, ya que escucha pensamientos negativos y oscuros de las personas que lo rodean.\r\n\r\nA medida que Satou intenta lidiar con su don y encontrar un propósito en su vida, se encuentra con una misteriosa chica llamada Hime. Hime también tiene una habilidad especial, puede ver el futuro de las personas al tocarlas. Juntos, Satou y Hime forman una conexión especial mientras exploran el significado de sus habilidades y cómo pueden impactar en las vidas de los demás.', 25.00, 'Yuka Nagate', 'Gentosha', '2005-06-06', 'GiftPlusMinus.jpg', 'Terror', 4.70, 10),
(33, 'Fantasmas y demonios', 'El manga presenta una serie de relatos oscuros y perturbadores que exploran el mundo de lo sobrenatural y lo macabro.\r\n\r\nCada historia se centra en la presencia de fantasmas, demonios o seres sobrenaturales que acechan a los protagonistas, desatando terror y caos en sus vidas. Junji Ito es conocido por su estilo artístico detallado y perturbador, así como por su capacidad para crear una atmósfera inquietante y claustrofóbica.\r\n\r\nA medida que los personajes se enfrentan a encuentros sobrenaturales, se ven envueltos en situaciones escalofriantes y se ven obligados a confrontar sus miedos más profundos. \"Fantasmas y demonios\" presenta una mezcla de horror psicológico, gore y elementos sobrenaturales que cautivan a los lectores.', 40.00, 'Junji Ito', 'Asahi Sonorama', '2017-12-19', 'FantasmasDemonios.jpeg', 'Terror', 6.40, 8),
(34, 'Beyond The Bad Dream', 'El terror vuelve a llamar a nuestra puerta con Beyond the Bad Dream! Un tomo único que nos trae 10 historias cortas terroríficas, que mezclan lo cotidiano con lo desconocido y cada una con giros impactantes, todo amenizado con gotas de humor negro, gore e influencias de los grandes del género.', 40.00, 'Sachiko Uguisu', 'Ivréa', '2015-05-30', 'BeyondTheBadDream.jpg', 'Terror', 5.00, 10),
(35, 'Ciudades y mansiones encantadas', 'En este manga, Ito explora el tema de los lugares malditos y embrujados, llenando las páginas con atmósferas inquietantes y personajes perturbadores.\r\n\r\nCada historia se desarrolla en un entorno urbano o en una mansión encantada, donde los protagonistas se enfrentan a fenómenos sobrenaturales y aterradores. Los edificios se convierten en personajes por derecho propio, con una presencia maligna y una capacidad para atormentar a quienes se aventuran en ellos.\r\n\r\nA través de su narrativa ingeniosa y su arte detallado, Junji Ito captura la sensación de opresión y la tensión constante que impregna estos lugares encantados. Las historias exploran temas como la obsesión, el miedo y la fragilidad de la realidad, sumergiendo a los lectores en un mundo de pesadillas y misterio.', 35.00, 'Junji Ito', 'Asahi Sonorama', '2002-07-22', 'CiudadesMasionesEncantadas.jpg', 'Terror', 6.60, 10),
(36, 'Naturaleza desbocada', 'La naturaleza puede ser fascinante pero también aterradora, y no hay mejor forma de comprobarlo que en los relatos de Junji Ito. En este tomo recopilatorio viajaremos por puentes cargados de antiguas tradiciones, bosques que esconden insólitas criaturas y poblados abandonados, visitaremos un nuevo hogar enmohecido, playas habitadas por horrendos monstruos, pantanos encantados y un valle repleto de misteriosos espejos. También echaremos un vistazo al pasado a través de una cápsula del tiempo, y unas extrañas criaturas revelarán oscuros secretos.', 24.00, 'Junji Ito', 'Shogakukan', '1998-09-19', 'NaturalezaDesbocada.jpg', 'Terror', 5.50, 10),
(37, 'Shigahime', 'La historia se desarrolla en un mundo postapocalíptico donde los seres humanos son perseguidos por criaturas sobrenaturales conocidas como \"Youma\". La protagonista, una joven llamada Shigahime, es una exorcista que se dedica a proteger a los humanos de estas amenazas. A medida que se adentra en su misión, descubre secretos oscuros sobre el origen de los Youma y se enfrenta a difíciles decisiones que desafían su sentido de la justicia y la moralidad. \"Shigahime\" combina acción, misterio y elementos sobrenaturales para ofrecer una historia emocionante y llena de giros inesperados.', 25.00, 'Sato Hirohisa', 'ECC Ediciones', '2022-11-15', 'Shigahime.jpg', 'Terror', 2.40, 10),
(38, 'Another', 'La historia sigue a Kōichi Sakakibara, un estudiante de secundaria que se traslada a una nueva escuela en la pequeña ciudad de Yomiyama. Pronto descubre que su clase está maldita por una misteriosa \"calamidad\" que ocurre todos los años y que lleva a la muerte de un estudiante. Kōichi se ve envuelto en una serie de eventos extraños y macabros mientras intenta descubrir la verdad detrás de la maldición y evitar sufrir el mismo destino que sus compañeros de clase. \"Another\" es conocido por su atmósfera inquietante, giros sorprendentes y un estilo artístico detallado que realza el ambiente escalofriante de la historia.', 45.00, 'Yukito Ayatsuji y Hiro Kiyohara', 'Kadokawa Shoten', '2010-05-04', 'another.jpg', 'Terror', 3.40, 10),
(39, 'The killer inside ', 'Eiji Urushima es un estudiante universitario cuyo lema es \"La vida es para disfrutarla\". El problema es que acarrea un terrible sino inconfesable. Cuando le toca enfrentarse a la cruda realidad acaba envuelto en una serie de atrocidades.', 55.00, 'Hajime Inoryû, Shôta Itô', 'KODANSHA', '2021-10-28', 'TheKillerInside.jpg', 'Terror', 6.30, 9),
(40, 'Dissolving classroom', 'El manga sigue la historia de dos hermanos, Yuuma y Chizumi, quienes tienen la extraña habilidad de disolver mentalmente a las personas que los rodean. A medida que la historia se desarrolla, los hermanos utilizan esta habilidad para causar caos y destrucción en su escuela y en otros entornos sociales. El manga explora temas oscuros y retorcidos, y presenta los impactos emocionales y psicológicos de los actos de los personajes. \"Dissolving Classroom\" es conocido por su atmósfera inquietante, su arte detallado y su narrativa perturbadora.', 45.00, 'Junji Ito', 'Asahi Sonorama', '2014-06-20', 'disolving.jpg', 'Terror', 5.30, 10),
(41, 'Fairy Tail', 'La historia se desarrolla en un mundo mágico donde los magos forman gremios para llevar a cabo misiones y proteger a las personas. El protagonista, Natsu Dragneel, es un joven mago del gremio Fairy Tail, conocido por su poderoso control sobre el fuego y su búsqueda para encontrar al dragón Igneel, quien lo crió.\r\n\r\nAcompañado por su compañera maga Lucy Heartfilia y otros miembros del gremio, Natsu se enfrenta a diversas misiones y desafíos, mientras descubre los secretos de su pasado y se enfrenta a enemigos poderosos. A lo largo de la serie, se exploran temas de amistad, lealtad, superación personal y la importancia del trabajo en equipo.', 45.00, 'Hiro Mashima', 'Kodansha Ltd', '2006-08-02', 'fairy tail.jpg', 'Shonen', 8.50, 10),
(42, 'Shingeki no Kyojin', 'El manga se desarrolla en un mundo donde la humanidad está al borde de la extinción debido a la existencia de gigantes humanoides conocidos como \"Titanes\". Estos seres devoran a los humanos sin razón aparente, lo que ha llevado a la humanidad a vivir detrás de enormes muros para protegerse.\r\n\r\nLa historia sigue a Eren Yeager, Mikasa Ackerman y Armin Arlert, tres jóvenes que sueñan con explorar el mundo exterior más allá de los muros y liberar a la humanidad de la amenaza de los Titanes. Sin embargo, su vida da un giro inesperado cuando el Titán Colosal aparece y destruye parte de los muros, permitiendo que los Titanes invadan la ciudad.', 60.00, 'Hajime Isayama', 'Kodansha', '2009-09-09', 'ataque.jpg', 'Shonen', 10.00, 36),
(43, 'Black Clover', 'La historia se desarrolla en un mundo donde la magia es común y cada persona nace con la capacidad de usarla, excepto Asta, el protagonista. Asta es un joven huérfano sin habilidad mágica aparente, pero posee una gran determinación y sueña con convertirse en el Rey Mago, el mago más poderoso del reino.\r\n\r\nAsta es aceptado en un gremio de magos llamado \"Black Bulls\", conocido por su comportamiento desordenado y su reputación menospreciada. Junto con su rival y amigo, Yuno, Asta se embarca en aventuras y misiones para demostrar su valía y encontrar su lugar en el mundo de la magia.\r\n\r\nA lo largo del manga, Asta y sus compañeros de los Black Bulls se enfrentan a enemigos poderosos, descubren secretos oscuros y desafían las normas establecidas por la sociedad mágica. La historia explora temas de amistad, superación personal y la importancia de la perseverancia y el trabajo en equipo.', 50.00, 'Yūki Tabata', 'Shueisha', '2015-02-16', 'BlackClover.jpg', 'Shonen', 8.80, 8),
(44, 'Gintama', 'La historia tiene lugar en un Japón alternativo, durante la era Edo, pero con una gran diferencia: la Tierra ha sido invadida por alienígenas conocidos como \"Amanto\", quienes han prohibido a los samuráis portar espadas.\r\n\r\nEl protagonista de la historia es Gintoki Sakata, un excéntrico samurái que trabaja como \"hombre para todo\" en una agencia de servicios. Junto a sus compañeros, Shinpachi Shimura y Kagura, se embarcan en todo tipo de aventuras absurdas y cómicas. A lo largo del manga, Gintoki se enfrenta a numerosos enemigos, desde criminales hasta poderosos guerreros espaciales, todo mientras lidia con situaciones hilarantes y desafíos inesperados.', 36.00, 'Hideaki Sorachi', 'Shueisha', '2003-12-08', 'Gintama.jpg', 'Shonen', 8.40, 10),
(45, 'Dr. Stone', 'La historia sigue a Senku Ishigami, un genio de la ciencia que despierta después de miles de años de estar petrificado junto con toda la humanidad. En un mundo donde la civilización ha sido reducida a la Edad de Piedra, Senku se propone reconstruir la sociedad y devolver la tecnología perdida.\r\n\r\nCon su vasto conocimiento científico, Senku comienza a desentrañar los misterios de la petrificación y a utilizar la ciencia para superar los desafíos que enfrenta. Junto a un variado grupo de personajes, incluyendo a su amigo Taiju y la inteligente Yuzuriha, Senku trabaja para revivir a otros humanos y construir una nueva era utilizando la ciencia como su arma principal.', 75.00, 'Riichiro Inagaki', 'Shueisha', '2017-03-06', 'DrStone.jpg', 'Shonen', 9.50, 7),
(46, 'Vinland Saga', 'La historia se desarrolla en la época vikinga y sigue la vida de Thorfinn, un joven vikingo sediento de venganza. Thorfinn se embarca en un viaje para confrontar a Askeladd, el líder de la banda de mercenarios a la que pertenecía su padre y responsable de su muerte.\r\n\r\nA medida que avanza la historia, Thorfinn se ve inmerso en conflictos políticos, batallas épicas y la búsqueda de un lugar llamado Vinland, una tierra pacífica y utópica. A lo largo de su viaje, Thorfinn se enfrenta a desafíos tanto físicos como emocionales, y se cuestiona su propia sed de venganza mientras busca un significado más profundo en su vida.', 60.00, 'Makoto Yukimura', 'Kodansha', '2005-04-13', 'Vinland.jpg', 'Shonen', 10.00, 42),
(47, 'Akame ga Kill!', 'La historia sigue a Tatsumi, un joven guerrero que se une a Night Raid, un grupo de asesinos rebeldes que se oponen al corrupto Imperio de Jaegers. Tatsumi y sus compañeros luchan contra los altos funcionarios y líderes del imperio para intentar cambiar el sistema y restaurar la justicia.\r\n\r\nA medida que avanza la trama, se exploran temas como la corrupción política, la desigualdad social y la moralidad. La historia está llena de intensas batallas, traiciones inesperadas y personajes con oscuros secretos. Cada miembro de Night Raid tiene habilidades y armas únicas, y deben enfrentar desafíos mortales mientras se enfrentan a enemigos poderosos.', 45.00, 'Takahiro', 'Square Enix', '2010-03-20', 'Akame.jpg', 'Shonen', 7.40, 10),
(48, 'Fire Force', 'La historia se desarrolla en un mundo donde los humanos pueden sufrir de combustión espontánea y convertirse en criaturas infernales llamadas \"Infernals\".\r\n\r\nLa trama sigue a Shinra Kusakabe, un joven que posee el poder de controlar y generar fuego con sus pies. Se une a la Compañía Especial de Bomberos, una organización dedicada a extinguir los Incendios Infernales y descubrir la verdad detrás de esta misteriosa amenaza. A medida que avanza la historia, Shinra descubre conspiraciones y secretos ocultos relacionados con los Incendios Infernales y su propio pasado.', 50.00, 'Atsushi Ohkubo', 'Kodansha', '2015-09-23', 'Fire.jpg', 'Shonen', 8.50, 10),
(49, 'Boruto: Naruto Next Generations', 'El manga sigue las aventuras de Boruto y sus amigos mientras se embarcan en misiones ninja, enfrentan desafíos personales y descubren los misterios que rodean a la Aldea Oculta de Konoha. Boruto debe encontrar su propio camino como ninja y superar las expectativas que se le imponen debido a su linaje y legado familiar.\r\n\r\nA lo largo de la historia, se exploran temas como la amistad, el crecimiento personal, el sacrificio y la importancia de mantener la paz en el mundo ninja. Los personajes queridos de \"Naruto\" también hacen apariciones en el manga, lo que brinda a los fanáticos la oportunidad de ver cómo han evolucionado a lo largo de los años.', 60.00, 'Masashi Kishimoto', 'Shueisha', '2016-05-09', 'Boruto.jpg', 'Shonen', 8.80, 7),
(50, 'Sword Art Online', 'La historia se desarrolla en un futuro cercano en el que los jugadores pueden sumergirse en un mundo virtual de realidad virtual llamado \"Sword Art Online\" (SAO).\r\n\r\nEl protagonista, Kirito, es uno de los miles de jugadores que se conectan al juego para vivir aventuras y explorar un vasto mundo lleno de monstruos y mazmorras. Sin embargo, pronto descubren que están atrapados en el juego y no pueden desconectarse. El creador de SAO, Akihiko Kayaba, les informa que la única forma de salir es completar todos los niveles y derrotar al jefe final.', 48.00, 'Reki Kawahara', 'Kadokawa', '2010-04-27', 'sao.jpg', 'Shonen', 8.00, 10),
(51, 'Tokyo Revengers', 'La historia sigue a Takemichi Hanagaki, un joven desempleado de 26 años que vive una vida llena de arrepentimientos. Un día, descubre que su exnovia, Hinata Tachibana, y su hermano menor, Naoto, han sido asesinados por una pandilla violenta conocida como los Tokyo Manji Gang.\r\n\r\nPero de alguna manera, Takemichi viaja en el tiempo y regresa a su etapa de estudiante de secundaria, justo antes de que los eventos trágicos ocurrieran. Determinado a cambiar el destino de sus seres queridos, Takemichi se propone unir fuerzas con la Tokyo Manji Gang y subir en sus filas para enfrentar a sus líderes y prevenir la tragedia.\r\n\r\nA lo largo de su viaje en el tiempo, Takemichi se reencuentra con sus antiguos amigos de la escuela secundaria, muchos de los cuales están involucrados con pandillas y tienen una influencia directa en los eventos futuros. Con cada encuentro, Takemichi lucha por cambiar el curso de la historia y evitar las tragedias que lo atormentan.', 65.00, ' Ken Wakui', 'Kodansha', '2017-03-01', 'tokyo.jpg', 'Shonen', 7.00, 9),
(52, 'Yu-Gi-Oh!', 'La historia sigue a Yugi Mutou, un estudiante de secundaria tímido y amante de los juegos. Yugi se encuentra en posesión de un antiguo artefacto egipcio conocido como el Rompecabezas del Milenio, que contiene el espíritu de un antiguo faraón llamado Yami Yugi.\r\n\r\nA medida que Yugi resuelve el Rompecabezas del Milenio, desata el poder del espíritu del faraón, quien se convierte en su alter ego durante los juegos. Juntos, Yugi y Yami Yugi se enfrentan a diversos desafíos en forma de juegos de cartas llamados \"Duelos de Monstruos\". Estos duelos son una mezcla de estrategia, habilidad y poderes místicos.', 52.00, 'Kazuki Takahashi', 'Shueisha', '1996-09-30', 'yugi.jpg', 'Shonen', 8.40, 9),
(53, 'The Promised Neverland', 'La historia se desarrolla en un orfanato aparentemente idílico llamado Grace Field House, donde los huérfanos Emma, Norman y Ray llevan una vida feliz junto a su \"mamá\" adoptiva, Isabella. Sin embargo, descubren un oscuro secreto que pone en peligro sus vidas.\r\n\r\nPronto se dan cuenta de que Grace Field House no es lo que parece, y que en realidad es una granja donde los niños son criados para ser alimentados a los demonios. Determinados a escapar de su terrible destino, Emma, Norman y Ray se unen con otros huérfanos para planificar su fuga y descubrir la verdad detrás de su mundo.', 56.00, 'Kaiu Shirai', 'Shueisha', '2016-08-01', 'neverland.jpg', 'Shonen', 6.50, 9),
(54, 'Noragami', 'La historia sigue a Yato, un dios menor que sueña con tener miles de seguidores y un templo propio. Sin embargo, su realidad es bastante diferente, ya que apenas tiene seguidores y trabaja como un dios de la entrega divina, realizando trabajos de limpieza y resolución de problemas por una pequeña tarifa.\r\n\r\nUn día, mientras está en busca de un trabajo, Yato se encuentra con Hiyori Iki, una estudiante de secundaria que tiene la capacidad de ver espíritus. Después de un encuentro accidentado, Hiyori queda atrapada entre el mundo de los dioses y los espíritus, y su alma se separa de su cuerpo. Con el fin de recuperar su forma original, Hiyori se convierte en la aprendiz de Yato y juntos emprenden diversas aventuras en el mundo espiritual.', 58.00, 'Adachitoka', 'Kodansha', '2010-12-06', 'noragami.jpg', 'Shonen', 8.40, 10),
(55, 'Chainsaw Man', 'La historia sigue a Denji, un joven que lucha por sobrevivir en un mundo oscuro y peligroso lleno de demonios. Para ganarse la vida, Denji se dedica a cazar demonios utilizando a su fiel compañera, una motosierra demoníaca llamada Pochita.\r\n\r\nSin embargo, la vida de Denji da un giro inesperado cuando es traicionado y asesinado por alguien en quien confiaba. Sin embargo, Pochita, el demonio de la motosierra, decide fusionarse con él y devolverle la vida como un híbrido humano-demonio conocido como Chainsaw Man.\r\n\r\nA partir de ese momento, Denji se une a una organización especial llamada Public Safety Devil Hunters, donde se le asignan misiones para cazar demonios y proteger a la humanidad. A medida que avanza la historia, Denji se enfrenta a desafíos cada vez mayores y descubre más sobre el mundo de los demonios, su propia naturaleza y su propósito en la vida.', 80.00, 'Tatsuki Fujimoto', 'Shueisha', '2018-12-03', 'chainsaw.jpg', 'Shonen', 9.60, 47),
(56, 'Eyeshield 21', 'La historia sigue a Sena Kobayakawa, un estudiante de secundaria tímido y poco atlético que se convierte en el corredor estrella del equipo de fútbol americano de su escuela, conocido como Deimon Devil Bats, bajo el seudónimo de Eyeshield 21.\r\n\r\nSena se une al equipo después de ser descubierto por Yoichi Hiruma, el quarterback y cerebro estratégico del equipo. Hiruma ve en Sena un potencial corredor veloz y habilidoso, y decide reclutarlo para mejorar las posibilidades del equipo en los partidos. Sin embargo, Sena debe ocultar su identidad como Eyeshield 21 usando una visera para evitar que su madre, una mujer sobreprotectora, descubra su participación en el deporte de alto impacto.', 40.00, 'Riichiro Inagaki', 'Shueisha', '2002-07-23', 'eye.jpg', 'Deporte', 6.40, 9),
(57, 'Prince of Tennis', 'La historia se centra en Ryoma Echizen, un joven prodigio del tenis que se une al equipo de tenis de la Secundaria Seishun Gakuen, conocida como Seigaku. A pesar de su corta estatura, Ryoma posee una increíble habilidad y talento en el tenis, heredado de su padre, quien fue un famoso jugador profesional.\r\n\r\nA lo largo del manga, Ryoma y sus compañeros del equipo de tenis de Seigaku participan en diversos torneos y enfrentan a rivales cada vez más fuertes. Ryoma se enfrenta a desafíos personales y debe superar obstáculos tanto dentro como fuera de la cancha para demostrar su valía como tenista.', 55.00, 'Takeshi Konomi', 'Shueisha', '1999-07-19', 'prince.jpg', 'Deporte', 8.30, 10),
(58, 'Major', 'La historia se centra en la vida de Goro Honda, un talentoso jugador de béisbol desde su infancia hasta su carrera profesional. La trama sigue la vida de Goro a medida que supera desafíos y enfrenta obstáculos en su camino hacia la grandeza en el béisbol.\r\n\r\nEl manga se divide en varias partes, cada una centrada en una etapa diferente de la vida de Goro. Comienza con su infancia y su pasión por el béisbol, luego sigue su crecimiento como jugador mientras se enfrenta a otros talentosos rivales y trabaja arduamente para mejorar sus habilidades.', 48.00, 'Takuya Mitsuda', 'Shogakukan', '1994-12-10', 'major.jpg', 'Deporte', 6.20, 9),
(59, 'Yowamushi Pedal', 'La historia se centra en Sakamichi Onoda, un estudiante de secundaria otaku y poco atlético que se une al club de ciclismo de su escuela, el Sohoku High Bicycle Club, después de descubrir su talento natural para el ciclismo de resistencia.\r\n\r\nA medida que se adentra en el mundo del ciclismo de competición, Sakamichi se enfrenta a desafíos físicos y mentales. Aunque al principio se consideraba a sí mismo un \"otaku débil\", se esfuerza por superarse a sí mismo y alcanzar el nivel de los ciclistas de élite.', 35.00, 'Wataru Watanabe', 'Akita Shoten', '2008-02-10', 'pedal.jpg', 'Deporte', 5.50, 10),
(60, 'Free!', 'La historia se centra en Haruka Nanase, un nadador talentoso y apasionado por el agua desde su infancia. Junto con sus amigos de la infancia, Makoto, Nagisa y Rin, formaron un equipo de natación llamado \"Iwatobi Swim Club\" en la escuela secundaria.\r\n\r\nA medida que avanzan en la escuela secundaria y se acercan al final de su tiempo juntos, Haruka y sus amigos enfrentan desafíos en su camino hacia la competencia en la natación. Además de lidiar con sus propias habilidades y metas individuales, también deben superar rivalidades, conflictos internos y descubrir el verdadero significado de la natación y la amistad.', 50.00, ' Kōji Ōji', 'Kyoto Animation', '2013-07-27', 'free.jpg', 'Deporte', 7.00, 10),
(61, 'Days', 'La historia sigue a Tsukushi Tsukamoto, un estudiante de secundaria sin habilidades atléticas ni talento para el fútbol. A pesar de esto, su pasión por el deporte lo lleva a unirse al club de fútbol de su escuela.\r\n\r\nTsukushi se encuentra con Jin Kazama, un talentoso y apasionado jugador de fútbol que se convierte en su mentor y compañero de equipo. Juntos, enfrentan desafíos en el campo, trabajan en su habilidad y forjan una amistad especial a través del deporte.', 57.00, 'Tsuyoshi Yasuda', 'Kodansha', '2013-04-14', 'days.jpg', 'Deporte', 6.40, 10);
INSERT INTO `producto` (`id`, `Titulo`, `Descripcion`, `Precio`, `Autor`, `Editorial`, `fecha_lanzamiento`, `imagenes`, `Categoría`, `Popularidad`, `stock`) VALUES
(62, 'All Out!!', 'El manga sigue la historia de Kenji Gion, un estudiante de primer año de preparatoria que es de baja estatura pero posee una gran pasión por el rugby. Aunque inicialmente no tiene experiencia en el deporte, decide unirse al equipo de rugby de su escuela y comienza a aprender y desarrollarse como jugador.\r\n\r\nKenji se encuentra con Sumiaki Iwashimizu, un estudiante de segundo año que es muy talentoso pero también tiene problemas de confianza debido a un pasado complicado. Juntos, junto con otros compañeros de equipo, enfrentan desafíos en el campo y trabajan en su habilidad y táctica para competir en los torneos de rugby.', 65.00, 'Shiori Amase', 'Kodansha', '2012-10-23', 'allout.jpg', 'Deporte', 6.70, 9),
(63, 'Area no Kishi', 'La historia gira en torno a Kakeru Aizawa, un estudiante de secundaria que solía ser un talentoso jugador de fútbol. Sin embargo, debido a un incidente traumático en su pasado, Kakeru decide renunciar al fútbol y centrarse en ser el mánager del equipo de fútbol de su escuela.\r\n\r\nA medida que la historia avanza, Kakeru se encuentra con diversas situaciones que lo llevan a reconsiderar su decisión y volver a jugar al fútbol. Con el apoyo de sus amigos y compañeros de equipo, se embarca en un viaje de redescubrimiento personal y lucha por convertirse en un jugador excepcional.', 37.00, 'Hiroaki Igano', 'Kodansha', '2006-07-20', 'area.jpg', 'Deporte', 5.50, 10),
(64, 'Baby Steps', 'La historia sigue a Eiichiro Maruo, un estudiante de secundaria que es muy dedicado a sus estudios y tiene poca experiencia en el ámbito deportivo. Un día, decide unirse al club de tenis de su escuela para mejorar su condición física y salir de su zona de confort.\r\n\r\nA medida que Eiichiro comienza a aprender y practicar tenis, descubre su pasión por el deporte y su deseo de convertirse en un jugador profesional. Aunque carece de habilidades naturales y talento, compensa esto con su diligencia, disciplina y mentalidad analítica. Con el tiempo, Eiichiro desarrolla técnicas de juego únicas y estrategias inteligentes que le permiten competir contra oponentes más fuertes.', 44.00, 'Hikaru Katsuki', 'Kodansha', '2007-10-02', 'baby.jpg', 'Deporte', 8.40, 10),
(65, 'Giant Killing', 'La historia se centra en el mundo del fútbol y sigue al equipo de fútbol profesional East Tokyo United (ETU), que ha caído en tiempos difíciles y se encuentra en la zona baja de la tabla.\r\n\r\nEl protagonista principal es Takeshi Tatsumi, un exjugador del ETU que se convierte en el nuevo entrenador del equipo. Tatsumi tiene una visión única del fútbol y está decidido a revivir el espíritu competitivo del ETU y llevarlo de regreso a la gloria. A pesar de las dudas y críticas iniciales, Tatsumi implementa un enfoque táctico innovador y recluta nuevos talentos para fortalecer el equipo.\r\n\r\nA lo largo de la historia, \"Giant Killing\" muestra los desafíos y obstáculos que enfrenta el equipo mientras luchan por superar a sus rivales más fuertes.', 46.00, 'Masaya Tsunamoto', 'Kodansha', '2007-10-27', 'giant.jpg', 'Deporte', 7.30, 10),
(66, 'Ashita no Joe', 'El manga cuenta la historia de Joe Yabuki, un joven problemático que se ve envuelto en el mundo del boxeo.\r\n\r\nJoe es un adolescente rebelde que se gana la vida como luchador callejero. Un día, después de involucrarse en una pelea, es arrestado y enviado a un centro de corrección juvenil. Allí, conoce a Danpei Tange, un antiguo boxeador retirado que ve el potencial de Joe para el boxeo profesional. Danpei se convierte en su entrenador y lo guía en su camino hacia la cima del boxeo.\r\n\r\nA lo largo de la historia, Joe enfrenta numerosos desafíos tanto dentro como fuera del ring. Lucha contra oponentes poderosos, se enfrenta a sus propios demonios internos y busca encontrar su verdadero lugar en el mundo del boxeo. A medida que avanza en su carrera, Joe se convierte en una figura legendaria, admirada por su tenacidad, valentía y habilidad para superar obstáculos.', 50.00, 'Ikki Kajiwara y Tetsuya Chiba', 'Kodansha', '1968-01-01', 'ashita.jpg', 'Deporte', 6.70, 10),
(67, 'Run with the Wind', 'La historia sigue a un grupo de estudiantes universitarios que se unen para formar un equipo de atletismo y participar en una importante carrera de relevos.\r\n\r\nLa trama se centra en Kakeru Kurahara, un estudiante universitario que es un talentoso corredor pero ha perdido su pasión por el deporte. Un día, es reclutado por Haiji Kiyose, un compañero de dormitorio, para formar parte de un equipo de atletismo con el objetivo de competir en la prestigiosa Hakone Ekiden, una carrera de relevos de larga distancia. A medida que el equipo se va formando y entrenando juntos, cada miembro enfrenta sus propios desafíos y luchas personales mientras buscan superarse a sí mismos y alcanzar la meta común.', 40.00, 'Shion Miura', 'Shueisha', '2007-06-02', 'run.jpg', 'Deporte', 5.80, 10),
(68, 'Ookiku Furikabutte ', 'La historia se centra en Ren Mihashi, un estudiante de secundaria que sufre de baja autoestima y falta de confianza debido a su experiencia pasada como lanzador de béisbol en su antiguo equipo. Sin embargo, cuando se une al equipo de béisbol de su nueva escuela secundaria, Nishiura High School, encuentra una oportunidad para redimirse y demostrar su verdadero potencial.\r\n\r\nA medida que Ren se involucra con el equipo de béisbol, se encuentra rodeado de compañeros de equipo apasionados y talentosos que lo ayudan a superar sus inseguridades. Bajo la guía del experimentado capitán del equipo, Takaya Abe, Ren comienza a desarrollar sus habilidades de lanzamiento y a aprender las complejidades estratégicas del juego. Juntos, el equipo de Nishiura se esfuerza por competir en torneos y enfrentarse a equipos poderosos, mientras lidian con sus propias luchas personales y fortalecen sus lazos de amistad.', 38.00, 'Asa Higuchi', 'Kodansha', '2003-04-14', 'okiku.jpg', 'Deporte', 5.70, 10),
(69, 'Air Gear', 'La historia se desarrolla en un futuro cercano donde el uso de patines motorizados llamados \"Air Treck\" se ha vuelto popular entre los jóvenes. El protagonista, Ikki Minami, es un chico de la calle que descubre el mundo de los Air Treck y se convierte en un \"Storm Rider\", participando en carreras y batallas de patinaje aéreo.\r\n\r\nIkki se une a un grupo de amigos conocido como \"Kogarasumaru\" y juntos se esfuerzan por convertirse en el mejor equipo de Air Treck. A medida que avanzan en el mundo de los Storm Riders, se enfrentan a desafíos, rivalidades y enfrentamientos con otros equipos poderosos. Además de las carreras, la serie también explora los conflictos personales y las relaciones entre los personajes, así como los secretos y misterios que rodean a los Air Treck y su origen.', 55.00, 'Ito Ōgure', 'Kodansha', '2002-11-06', 'air.jpg', 'Deporte', 8.30, 10),
(70, 'Initial D', 'La historia se centra en Takumi Fujiwara, un estudiante de secundaria que trabaja a tiempo parcial en una gasolinera durante el día y se convierte en un talentoso corredor callejero por la noche.\r\n\r\nAunque Takumi parece ser un chico común, tiene una habilidad natural para conducir gracias a los años de experiencia manejando el auto de reparto de tofu de su padre por las empinadas y sinuosas carreteras de montaña. Sin darse cuenta, Takumi se convierte en una leyenda de las carreras callejeras cuando su talento y habilidades de conducción son descubiertos por un equipo de corredores profesionales.\r\n\r\nLa serie sigue las aventuras de Takumi mientras participa en emocionantes carreras callejeras y se enfrenta a diversos oponentes, cada uno con su propio estilo de conducción y automóvil único.', 60.00, 'Shuichi Shigeno', 'Kodansha', '1995-06-06', 'initial.jpg', 'Deporte', 4.60, 10),
(71, 'kaichou wai sama', 'La historia se desarrolla en el instituto Seika, donde Misaki Ayuzawa, una estudiante destacada y presidenta del consejo estudiantil, se ha ganado una reputación estricta y exigente. Sin embargo, lo que nadie sabe es que fuera de la escuela, Misaki trabaja a tiempo parcial en un café de maids para ayudar económicamente a su familia.\r\n\r\nLa trama se centra en la vida de Misaki y su encuentro con Takumi Usui, un chico popular y guapo en la escuela. A medida que Takumi descubre el secreto de Misaki, comienza a mostrar un interés especial en ella y se convierte en su principal seguidor y protector. Aunque al principio Misaki se muestra reacia a aceptar la atención de Takumi, con el tiempo comienza a desarrollarse una historia de amor complicada entre ellos.', 28.00, 'Hiro Fujiwara', 'Hakusensha', '2006-03-10', 'Kaichouwamaidsama.jpg\r\n', 'shoujo', 5.40, 10),
(72, 'My Dress-Up Darling', 'La historia sigue a Wakana Gojo, un estudiante de secundaria que es fanático de la creación de muñecas. Un día, se encuentra con Marin Kitagawa, una compañera de clase que es popular pero guarda un secreto: también es una apasionada de la creación de trajes para muñecas. Juntos, comienzan a explorar su amor por la confección de ropa para muñecas y se embarcan en una emocionante aventura llena de amistad, pasión y autodescubrimiento. El manga combina elementos de comedia, romance y pasatiempos creativos en una historia encantadora y entretenida.', 70.00, 'Shinichi Fukuda', 'Square Enix', '2018-06-12', 'mydrees.jpg', 'Shoujo', 8.80, 8),
(73, 'Ouran High School Host Club', 'La historia sigue a Haruhi Fujioka, una estudiante de clase trabajadora que recibe una beca para asistir a la prestigiosa Escuela Secundaria Ouran, habitada por estudiantes de familias adineradas. Por accidente, Haruhi termina rompiendo un costoso jarrón perteneciente al club de anfitriones de la escuela y, para pagar su deuda, es reclutada como miembro del club.\r\n\r\nA pesar de que Haruhi es en realidad una chica, se ve obligada a hacerse pasar por un hombre y entretener a las clientas femeninas del club. A medida que se desarrolla la historia, Haruhi se encuentra en situaciones cómicas y románticas junto con los otros miembros extravagantes y encantadores del club de anfitriones. \"Ouran High School Host Club\" es conocido por su humor, personajes memorables y las dinámicas entre ellos, así como por abordar temas como la identidad, las relaciones y las diferencias sociales.', 30.00, 'Bisco Hatori', 'Hakusensha', '2002-09-22', 'hostclub.jpg', 'shoujo', 4.90, 10),
(74, 'Ore Monogatari', 'La historia gira en torno a Takeo Gouda, un estudiante de preparatoria con una apariencia imponente pero un corazón tierno. Aunque es amable y valiente, Takeo siempre ha sido rechazado por las chicas debido a su apariencia intimidante.\r\n\r\nSin embargo, un día, Takeo rescata a una chica llamada Rinko Yamato de un acosador en el tren. A diferencia de las otras chicas, Rinko no se deja llevar por la apariencia de Takeo y se siente atraída por su personalidad y su corazón amable. A partir de ese momento, comienza una dulce historia de amor entre Takeo y Rinko.', 40.00, 'Kazune Kawahara', 'Shueisha', '2012-02-25', 'ore.jpg\r\n', 'Shoujo', 5.30, 10),
(75, 'Lovely Complex', 'La historia se centra en Risa Koizumi, una chica alta, y Atsushi Otani, un chico bajo, quienes se conocen en la escuela secundaria y se convierten en compañeros de clase. Debido a su diferencia de estaturas, a menudo son objeto de burlas y comparaciones. A pesar de sus diferencias, Risa y Otani desarrollan una amistad inesperada y comienzan a ayudarse mutuamente en sus problemas amorosos.\r\n\r\nA medida que su amistad se fortalece, Risa y Otani comienzan a darse cuenta de que sus sentimientos podrían ir más allá de la amistad. Sin embargo, sus propias inseguridades y el miedo al rechazo les impiden confesar sus verdaderos sentimientos el uno al otro. A lo largo del manga, los personajes enfrentarán desafíos emocionales, aprenderán a aceptarse a sí mismos y lucharán por superar las barreras que se interponen en su camino hacia el amor verdadero.', 32.00, 'Aya Nakahara', 'Shūeisha', '2001-09-13', 'love.jpg', 'shoujo', 6.20, 10),
(76, 'Special A', 'La historia de Hikari Hanazono, una estudiante excepcionalmente talentosa y competitiva, quien está decidida a superar a Kei Takishima, su rival de toda la vida y el estudiante número uno de la academia. Ambos son miembros del grupo élite conocido como la \"Special A\", compuesto por los siete estudiantes de mayor rendimiento académico en la escuela. A medida que compiten en diversos desafíos, Hikari se da cuenta de que sus sentimientos hacia Kei van más allá de la rivalidad y surge una complicada historia de amor y comedia romántica. A lo largo del manga, los personajes enfrentan situaciones divertidas, románticas y emocionales mientras buscan el éxito académico y descubren el verdadero significado de la amistad y el amor.', 40.00, 'Maki Minami', 'Hakusensha', '2003-04-05', 'special.jpg', 'Shoujo', 3.60, 10),
(77, 'Itazura Na Kiss', 'La historia sigue la vida de Kotoko Aihara, una estudiante de preparatoria poco inteligente pero muy enamorada de Naoki Irie, el chico más popular y brillante de su escuela. Después de una confesión rechazada, un terremoto destruye la casa de Kotoko y ella y su padre se mudan a la casa de un amigo de su padre, donde resulta que Naoki también vive. A partir de ese momento, Kotoko hará todo lo posible para conquistar el corazón de Naoki y demostrarle que, a pesar de su diferencia en inteligencia, son el uno para el otro. A lo largo de la historia, se exploran las dificultades y los altibajos del amor adolescente, con momentos divertidos, románticos y emocionales.', 28.00, 'Kaoru Tada', 'Shūeisha', '1990-06-25', 'itazura.jpg', 'Shoujo', 6.70, 50),
(78, 'Vampire Knight', 'La historia se centra en Yuki Cross, una estudiante de la Academia Cross, una escuela que alberga tanto a humanos como a vampiros. Yuki se convierte en la guardiana del secreto de la academia: el hecho de que el director de la escuela, Kaname Kuran, es un vampiro. A medida que avanza la trama, se desarrolla un triángulo amoroso entre Yuki, Kaname y Zero Kiryu, otro estudiante que odia a los vampiros. Con una mezcla de romance, misterio y acción, \"Vampire Knight\" ofrece una intrigante historia sobre la coexistencia entre humanos y vampiros, y los desafíos que enfrentan los personajes principales mientras desentrañan los secretos de su mundo.', 39.00, 'Matsuri Hino', 'Hakusensha', '2004-11-24', 'vampire.jpg', 'shoujo', 4.70, 9),
(79, 'Sailor Moon', 'La historia sigue las aventuras de Usagi Tsukino, una joven estudiante de secundaria que descubre que es la reencarnación de la legendaria guerrera Sailor Moon. Junto a un grupo de chicas llamadas las Sailor Senshi, Usagi lucha contra fuerzas malignas para proteger la Tierra y encontrar a la princesa lunar perdida. El manga combina elementos de romance, amistad, acción y fantasía, y ha sido elogiado por su representación de poder femenino y mensajes positivos. \"Sailor Moon\" ha tenido un gran impacto en la cultura pop y ha sido adaptado en anime, películas y otras formas de medios.', 42.00, 'Naoko Takeuchi', 'Kōdansha', '1991-08-12', 'salior.jpg', 'Shoujo', 8.70, 10),
(80, 'Toradora', 'La historia sigue a Ryuuji Takasu, un estudiante de instituto con una apariencia intimidante pero de buen corazón, y a Taiga Aisaka, una chica pequeña pero de temperamento fuerte. Ambos se encuentran en una situación peculiar cuando descubren que están enamorados de los mejores amigos del otro. Deciden ayudarse mutuamente en sus respectivas relaciones amorosas, creando una extraña alianza que los llevará a enfrentar diversas situaciones cómicas y románticas. \"Toradora\" combina momentos de comedia, drama y romance, explorando temas como la amistad, el crecimiento personal y el verdadero significado del amor.', 40.00, 'Yuyuko Takemiya y Zekkyo', 'ASCII Media Works', '2007-03-26', 'tora.jpg', 'Shoujo', 4.60, 9),
(81, 'Natsume Yuujinchou Shi', 'El manga sigue la historia de Takashi Natsume, un joven que tiene la capacidad de ver espíritus desde que era niño. Hereda un libro llamado \"Libro de los amigos\" de su abuela, Reiko, que contenía nombres de espíritus que ella había derrotado y controlado. Con el tiempo, Takashi se embarca en una aventura para liberar a los espíritus de sus nombres en el libro y devolverles la libertad. Durante su viaje, se encuentra con criaturas sobrenaturales y otros humanos con conexiones con el mundo espiritual. \"Natsume Yuujinchou Shi\" es una historia conmovedora que combina elementos de fantasía, drama y amistad mientras Takashi descubre más sobre sí mismo y su conexión con el mundo espiritual.', 33.00, 'Yuki Midorikawa', 'Hakusensha', '2009-01-02', 'natsume.jpg', 'Shoujo', 5.60, 10),
(82, 'Romeo x Juliet', 'La historia se desarrolla en la ciudad flotante de Neo Verona, donde los Montesco y los Capuleto, dos familias rivales, luchan por el poder. En medio de esta rivalidad, Romeo Montesco y Julieta Capuleto se encuentran y se enamoran a primera vista, desafiando así las barreras impuestas por sus familias. A medida que su amor prohíbido florece, se ven envueltos en un mundo de intriga política, tragedia y destino, enfrentando pruebas y sacrificios para proteger su amor y encontrar la paz en una sociedad en conflicto.', 30.00, 'Reiko Yoshida', 'Kadokawa Shōten', '2007-04-04', 'romeo.jpg', 'Shoujo', 5.60, 10),
(83, 'Watashi ga Motete', 'La historia sigue a Kae Serinuma, una estudiante de secundaria y ávida fujoshi (fan de anime y manga) que repentinamente se convierte en una chica hermosa después de perder peso. A raíz de su transformación, varios chicos populares comienzan a mostrar interés en ella, pero Kae solo tiene ojos para los romances ficticios en los que se sumerge en su mundo otaku. El manga sigue las hilarantes y a veces complicadas situaciones en las que Kae se encuentra mientras trata de equilibrar su amor por los personajes de anime y manga con las relaciones reales.', 40.00, 'Junko', 'Kōdansha', '2013-10-13', 'watashi.jpg', 'shoujo', 5.60, 10),
(84, 'Inuyasha ', 'La historia se centra en una estudiante de secundaria llamada Kagome Higurashi, quien se ve transportada misteriosamente al pasado feudal de Japón. Allí, se encuentra con un medio demonio llamado Inuyasha y juntos emprenden una búsqueda para encontrar los fragmentos de la Joya de Cuatro Almas y evitar que caiga en manos equivocadas.\r\n\r\nA lo largo de su viaje, Kagome y Inuyasha se enfrentan a numerosos demonios, se unen a un variado grupo de aliados y descubren secretos sobre su propia identidad y el pasado del mundo al que han sido transportados. Además, se desarrolla una compleja relación entre Kagome e Inuyasha, llena de conflictos y momentos emocionales.', 35.00, 'Rumiko Takahashi', 'Shōgakukan', '1996-11-18', 'inuyasha.jpg', 'Shoujo', 5.90, 7),
(85, 'GeGeGe no Kitarō', 'La historia sigue las aventuras de Kitarō, un niño yōkai (espíritu sobrenatural) con un ojo izquierdo humano y el derecho en forma de bola de fuego. Kitarō se enfrenta a una amplia variedad de monstruos y yōkai, protegiendo tanto a los humanos como a los yōkai de amenazas sobrenaturales. El manga aborda temas de convivencia pacífica entre humanos y criaturas sobrenaturales, y también aborda cuestiones sociales y políticas en Japón. Desde su publicación inicial en 1960, \"GeGeGe no Kitarō\" ha sido adaptado a varias series de anime, películas y otros medios, y se ha convertido en un clásico del género de los yōkai.', 40.00, 'Shigeru Mizuki', 'Kōdansha', '1959-02-11', 'gege.jpg', 'Terror', 6.70, 10),
(86, 'Uzumaki', 'La historia se desarrolla en una pequeña ciudad llamada Kurôzu-cho, que se ve afectada por una extraña maldición en forma de espirales. Los residentes de la ciudad comienzan a obsesionarse con las espirales de diferentes formas, lo que desencadena una serie de eventos terroríficos y grotescos. El protagonista, Kirie Goshima, junto con su amigo Shuichi Saito, intenta desentrañar el misterio detrás de la maldición y escapar de su influencia destructiva. A medida que la trama avanza, se exploran temas como la obsesión, la locura y el poder del miedo. \"Uzumaki\" se destaca por su arte detallado y perturbador, así como por su narrativa inquietante que sumerge a los lectores en un mundo de horror psicológico.', 39.00, 'Junji Ito', 'Shogakukan', '1998-09-30', 'uzumaki.jpg', 'Terror', 6.30, 10),
(87, 'The Ring', 'La historia gira en torno a un misterioso video que contiene una maldición mortal. Se dice que aquellos que ven el video reciben una llamada telefónica que les anuncia que morirán en siete días. El manga sigue a varios personajes que se ven atrapados en la maldición y buscan desentrañar el origen y la forma de romperla antes de que llegue su fatídico destino. A medida que los personajes se adentran en la oscura historia detrás del video y se enfrentan a una serie de horrores sobrenaturales, la tensión y el suspenso aumentan. \"The Ring\" es conocido por su atmósfera inquietante, su narrativa intrigante y su capacidad para mantener a los lectores en vilo a medida que se desvelan los secretos y se revela el verdadero alcance de la maldición.', 25.00, 'Koji Suzuki', 'Shūeisha', '1991-05-31', 'ring.jpg', 'Terror', 4.30, 10),
(88, 'Bukita-kun', '¿Quién dijo que los zombies no tienen su corazoncito? En esta ocasión, tenemos como protagonista a un muerto viviente muy especial que busca desesperadamente encontrar a su verdadero amor. Un amor que intentará atrapar de todas las formas más macabras posibles.', 39.00, 'Kanako Inuki', 'Hakusensha', '1992-11-13', 'bukita.jpg', 'Terror', 4.90, 10),
(89, 'El Niño Gusano', 'La historia se desarrolla en un futuro cercano y sigue las aventuras de un joven llamado Koji, apodado \"El Niño Gusano\" debido a su habilidad para trepar por cualquier superficie. Koji vive en una ciudad costera en ruinas, donde los habitantes se dedican principalmente a la pesca y a explorar los restos de barcos y aviones abandonados. A medida que Koji se adentra en este mundo postapocalíptico, se encuentra con extrañas criaturas, desafíos emocionales y secretos ocultos que podrían cambiar su percepción del mundo. Con una narrativa lenta y contemplativa, \"El Niño Gusano\" combina elementos de ciencia ficción, aventura y exploración personal para ofrecer una historia única y cautivadora.', 45.00, 'Hideshi Hino', 'Shogakukan', '1987-01-30', 'gusano.jpg', 'Terror', 5.40, 10),
(90, 'Monster', 'La historia sigue al brillante cirujano Kenzo Tenma, quien se encuentra en una encrucijada moral cuando debe elegir entre salvar la vida de un niño o la de un importante político. Después de tomar una decisión, Tenma se enfrenta a las consecuencias devastadoras cuando el niño, ahora adulto, se convierte en un asesino en serie conocido como \"El Monstruo\". Determinado a enmendar su error y detener al asesino, Tenma se embarca en una búsqueda para capturar a \"El Monstruo\" y desentrañar la verdad detrás de su motivación y su conexión con una misteriosa organización. A lo largo de la historia, se exploran temas como la naturaleza humana, la moralidad y la búsqueda de la redención, mientras Tenma se adentra en un mundo oscuro y peligroso en su intento por detener a \"El Monstruo\". \"Monster\" es un thriller psicológico lleno de intriga, suspense y giros sorprendentes que mantendrán a los lectores en vilo hasta el final.', 40.00, 'Naoki Urasawa', 'Shōgakukan', '1995-03-30', 'monster.jpg', 'Terror', 4.50, 10),
(91, 'Hellsing ', 'La historia sigue a la Organización Hellsing, una agencia secreta del gobierno británico encargada de proteger al país de amenazas sobrenaturales, especialmente de los vampiros. Al frente de la organización se encuentra la poderosa vampira Alucard, un ser inmortal y letal que se enfrenta a criaturas oscuras y siniestras.\r\n\r\nLa trama se desarrolla cuando la joven policía Seras Victoria es transformada en vampiro por Alucard y se une a la Organización Hellsing. Juntos, Alucard y Seras luchan contra una serie de enemigos despiadados, incluyendo a otros vampiros y a una misteriosa organización llamada Millennium.', 26.00, 'Kouta Hirano', 'Shōnen Gahōsha', '1998-06-04', 'hellsing.jpg', 'Terror', 5.50, 9),
(92, 'Goth', 'La historia sigue a dos personajes principales: un estudiante de preparatoria llamado Morino, que tiene una fascinación morbosa por los crímenes y asesinatos, y una misteriosa chica llamada Yoru, quien parece estar involucrada en una serie de homicidios sin resolver.\r\n\r\nA medida que Morino y Yoru se conocen, comienzan a explorar los oscuros rincones de la mente humana y a desentrañar los misterios detrás de los asesinatos. Juntos, investigan los casos, analizan las motivaciones de los criminales y buscan entender los límites de la maldad y la depravación.', 40.00, 'Otsuichi', 'Kadokawa Shoten', '2004-03-26', 'goth.jpg', 'Terror', 6.90, 9),
(93, 'Jigoku Shōjo', 'La historia gira en torno a una leyenda urbana que involucra a una misteriosa página web conocida como \"Hotline to Hell\". Se dice que si visitas esta página a medianoche y escribes el nombre de alguien que te está causando un gran sufrimiento, la venganza caerá sobre esa persona y será enviada al infierno.\r\n\r\nLa protagonista de la historia es Ai Enma, una joven misteriosa que se presenta como Jigoku Shōjo, la Chica del Infierno. Ella se dedica a llevar a cabo la venganza de aquellos que contactan con la página web, pero a un alto precio: aquellos que buscan su ayuda también serán condenados al infierno después de su muerte.\r\n\r\nA medida que la historia avanza, se exploran diferentes casos de personas que recurren a Jigoku Shōjo en busca de venganza. ', 25.00, 'Miyuki Etō', 'Gentosha Comics', '2005-11-30', 'girl.jpg', 'Terror', 4.50, 8),
(94, 'Helter Skelter', 'La historia se centra en la vida de Liliko, una famosa modelo y actriz cuya belleza es considerada icónica. Sin embargo, detrás de su aparente perfección y glamour se esconde una verdad oscura.\r\n\r\nLiliko se somete a múltiples cirugías plásticas para mantener su apariencia joven y hermosa, pero su obsesión por la belleza y la fama la lleva a una espiral autodestructiva. A medida que su cuerpo y su mente se deterioran, se enfrenta a las consecuencias físicas y emocionales de sus decisiones.\r\n\r\nLa historia de \"Helter Skelter\" aborda temas como la belleza artificial, los estándares de belleza impuestos por la sociedad y la presión constante que sufren las personas famosas para mantener una imagen perfecta.', 40.00, 'Kyoko Okazaki', 'Hakusensha', '2003-10-08', 'helter.jpg', 'Terror', 6.70, 9),
(95, 'I Am Hero', 'La historia sigue a Hideo Suzuki, un asistente de dibujante de manga que vive una vida monótona y sin rumbo. Sin embargo, su vida da un giro inesperado cuando un brote de una extraña enfermedad comienza a convertir a las personas en horribles criaturas sedientas de sangre y con comportamientos violentos.\r\n\r\nHideo se encuentra atrapado en medio de un apocalipsis zombi y se ve obligado a enfrentarse a situaciones peligrosas y a lidiar con su propia cordura mientras intenta sobrevivir. A medida que la sociedad se desmorona y la civilización se desvanece, Hideo lucha por mantener su humanidad intacta y encontrar un propósito en este nuevo mundo lleno de caos y muerte.', 50.00, 'Kengo Hanazawa', 'Shōgakukan', '2009-09-30', 'hero.jpg', 'Terror', 8.90, 5),
(96, 'Franken Fran', 'La historia gira en torno a Fran Madaraki, una talentosa cirujana y científica loca que se dedica a realizar experimentos y procedimientos médicos extremos para ayudar a las personas en situaciones desesperadas.\r\n\r\nSin embargo, las \"soluciones\" de Fran a menudo resultan en grotescas y retorcidas aberraciones. A medida que los pacientes buscan la ayuda de Fran para curar sus problemas físicos y emocionales, se ven envueltos en situaciones surrealistas y macabras. La línea entre la vida y la muerte, la belleza y la fealdad, la humanidad y la monstruosidad se difumina en este mundo donde los límites morales son desafiados.', 35.00, 'Katsuhisa Kigitsu', 'Akita Shoten', '2006-11-22', 'frank.jpg', 'Terror', 4.50, 10),
(97, 'Gantz', 'La historia sigue a Kei Kurono, un estudiante de preparatoria que se encuentra en un mundo peligroso y desconocido después de morir en un accidente junto a un amigo. Allí, son reclutados por una misteriosa esfera negra llamada Gantz.\r\n\r\nGantz les ofrece la oportunidad de regresar a la vida, pero con una condición: deben participar en cacerías mortales contra criaturas alienígenas y otros enemigos peligrosos. Armados con trajes especiales y armas avanzadas, Kei y otros participantes se enfrentan a situaciones extremas y sangrientas donde la vida y la muerte están constantemente en juego.', 60.00, 'Hiroya Oku', 'Shūeisha', '2000-12-02', 'gantz.jpg', 'Terror', 7.80, 10),
(98, 'Homunculus', 'La historia sigue a Susumu Nakoshi, un hombre desilusionado y solitario que se ve envuelto en un experimento peligroso. Un día, es abordado por un extraño hombre que le ofrece la oportunidad de participar en un experimento que promete despertar su \"sexto sentido\".\r\n\r\nAceptando la propuesta, Susumu se somete a una cirugía en la cual se le implanta un trozo de tejido cerebral en el área de su hipotálamo. A partir de entonces, comienza a experimentar alucinaciones y visiones perturbadoras, así como una habilidad especial para ver los deseos y secretos más oscuros de las personas a través de sus rostros.', 37.00, 'Hideo Yamamoto', 'Shogakukan', '2004-04-30', 'homun.jpg', 'Terror', 6.80, 10),
(99, 'Fruits Basket', 'La historia gira en torno a Tohru Honda, una joven huérfana que se ve obligada a vivir en una tienda de campaña después de la muerte de su madre. Sin embargo, un encuentro fortuito con los miembros de la familia Sohma cambiará su vida para siempre.\r\n\r\nTohru descubre que los Sohma están malditos por los espíritus de los animales del zodiaco chino. Cada miembro de la familia se transforma en el animal del zodiaco correspondiente cuando son abrazados por alguien del sexo opuesto o cuando están bajo estrés emocional. Tohru promete guardar el secreto de los Sohma y, a cambio, es invitada a vivir en la casa de Shigure Sohma.\r\n\r\nA medida que Tohru se adentra en la vida de los Sohma, conoce a los diferentes miembros de la familia y descubre sus historias personales y traumas. A través de su amabilidad y compasión, Tohru intenta romper las cadenas de la maldición y ayudar a los Sohma a sanar emocionalmente.', 58.00, 'Natsuki Takaya', 'Hakusensha', '1998-07-18', 'fruits.jpg', 'Shoujo', 6.40, 10),
(100, 'School-Live', 'La trama sigue a un grupo de chicas que parecen ser estudiantes de secundaria normales, pero en realidad están atrapadas en una situación postapocalíptica. La protagonista, Yuki Takeya, es una joven alegre y optimista que cree que está viviendo una vida escolar normal junto con sus amigas en el Club de la Vida Escolar. Sin embargo, la realidad es mucho más sombría, ya que su escuela está plagada de zombis y deben luchar por su supervivencia.\r\n\r\nLa historia explora las emociones y los desafíos a los que se enfrentan las chicas mientras intentan mantener la apariencia de una vida normal en medio del caos. La narrativa alterna entre momentos de alegría y diversión, y momentos de tensión y horror a medida que descubren los secretos de su escuela y luchan contra las amenazas que acechan en cada esquina.', 52.00, 'Norimitsu Kaihou', 'Houbunsha', '2012-01-27', 'school.jpg', 'Terror', 6.40, 7),
(109, ' Banana Split', 'Banana Split Banana SplitBanana SplitBanana SplitBanana Split Banana Split', 30.00, 'mipne', 'asdasdas', '2023-06-30', 'fd773cac18b600365bc107d2220af36f.jpg', 'shonen', NULL, 30),
(110, 'Banana Split12', 'asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas asdasasas', 35.50, 'asdasasas', 'asdasasas', '2023-07-14', 'ed262a53e011d5cbcd13ed06c3904c99.jpg', 'Shonen', 6.00, 50);

-- --------------------------------------------------------

--
-- Table structure for table `usuarios`
--

CREATE TABLE `usuarios` (
  `id` int(11) NOT NULL,
  `nombre` varchar(60) DEFAULT NULL,
  `apellido` varchar(60) DEFAULT NULL,
  `email` varchar(30) DEFAULT NULL,
  `password` varchar(60) DEFAULT NULL,
  `telefono` varchar(10) DEFAULT NULL,
  `direccion` varchar(60) DEFAULT NULL,
  `admin` tinyint(1) DEFAULT NULL,
  `confirmado` tinyint(1) DEFAULT NULL,
  `token` varchar(15) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `usuarios`
--

INSERT INTO `usuarios` (`id`, `nombre`, `apellido`, `email`, `password`, `telefono`, `direccion`, `admin`, `confirmado`, `token`) VALUES
(1, 'admin', 'poderoso', 'admin@correo.com', '$2y$10$aIcK4xdxMxIhBdzGRnwhx.zxF.nvUNRQUANf1prrbHu9QhE5gdmOS', '987654123', NULL, 1, 1, ''),
(2, 'Ronaldo', 'Peraira', 'rodriguez@gmail.com', '$2y$10$JImNu/sVt/yYEiTGA.2PV.sxJ6Nvxtdpoaq.NJDwyWp3cc9mo7vSq', '9999999', 'Jr. Comandante Jimenez 501-397, Magdalena del Mar 15073', 0, 1, ''),
(5, 'Alberto', 'Aguilar', 'alberto_123@correo.com', '$2y$10$j.MPCcwEwObEWq.I.rOkye4biq2YnFIg6nlr3EMCjb9Be0Hgy5Y0u', '973807605', 'C. Berlín 900-952, Miraflores 15074', 0, 1, ''),
(6, 'Mario', 'Broos', 'mario_123@gmail.com', '$2y$10$wYfVOqakhxY2fj2a0lCEsuuzCekTVgo1XHlMvWEiYU1pwU5PbJ6vC', '987536214', 'Dulanto 144-146, Lima 15047', 0, 1, ''),
(7, 'Maria', 'Jose', 'maria@gmail.com', '$2y$10$qxnfkVWEZgdcOhiSjr8Pcu.DllwKgyP2xpEjXewYMQEqmvsiOxooG', '9514785632', 'Conde de Castellar 297-189, Lima 15049', 0, 1, ''),
(8, 'Pablo', 'Martinez', 'pablo_123@gmai.com', '$2y$10$STdf1Tn2M/DbAZmVPHg60OwrF6QIyeye35zEEYNP1nH4bxMBt33Eu', '987471485', '2A, San Juan de Miraflores 15801', 0, 1, ''),
(9, 'Marcia', 'Garcia', 'marcia@gmail.com', '$2y$10$rdEt5/ThMfBxZxTL0JbRHeKZEs2n4cuZtt79sgpjWa8D4e9qnkeVW', '951478524', 'Los caminos del inca #145', 0, 1, ''),
(11, 'Lucho', 'Salazar', 'lucho_123@outlook.com', '$2y$10$K2KxmO8Zn9nD7DKNMEumMOkv9DZurOg/FTJr8Hz/gXdIBXegvYZj2', '973807605', 'Avenida Cesar Vallejo #362', 0, 1, ''),
(12, 'Alejandro', 'Morena', 'alejan@gmail.com', '$2y$10$aWXveOx3rGRnrySztj5Fruq0GU3LeN5933flGtUyJq4bzQHbTqzBK', '973807605', 'Avenida Zepita #362', 0, 1, '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `compra`
--
ALTER TABLE `compra`
  ADD PRIMARY KEY (`id`),
  ADD KEY `compra_ibfk_1` (`idUsuario`);

--
-- Indexes for table `detalle_compra`
--
ALTER TABLE `detalle_compra`
  ADD PRIMARY KEY (`id`),
  ADD KEY `manga_id` (`manga_id`),
  ADD KEY `compra_id` (`compra_id`);

--
-- Indexes for table `producto`
--
ALTER TABLE `producto`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `usuarios`
--
ALTER TABLE `usuarios`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `compra`
--
ALTER TABLE `compra`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `detalle_compra`
--
ALTER TABLE `detalle_compra`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `producto`
--
ALTER TABLE `producto`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=111;

--
-- AUTO_INCREMENT for table `usuarios`
--
ALTER TABLE `usuarios`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `compra`
--
ALTER TABLE `compra`
  ADD CONSTRAINT `compra_ibfk_1` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL ON UPDATE SET NULL;

--
-- Constraints for table `detalle_compra`
--
ALTER TABLE `detalle_compra`
  ADD CONSTRAINT `detalle_compra_ibfk_1` FOREIGN KEY (`manga_id`) REFERENCES `producto` (`id`) ON DELETE SET NULL ON UPDATE SET NULL,
  ADD CONSTRAINT `detalle_compra_ibfk_2` FOREIGN KEY (`compra_id`) REFERENCES `compra` (`id`) ON DELETE SET NULL ON UPDATE SET NULL;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
